name: test
description: test group

structure:
  root:
    - 'Dockerfile'
    - 'docker-compose.yml'
    - bin:
      - 'console'
    - src:
      - PhpScff:
        - 'Kernel.php'
        - Command:
          - 'AddCommand.php'
          - 'EditCommand.php'
        - FileSystem:
          - 'Directory.php'
          - 'File.php'

